### ISSUE TITLE
Support `/`s in `server_name`

### ISSUE THREAD

**Issue by brian6932** [radioactiveAHM/DnsSafeguard#4]
So I use NextDNS, and you can optionally provide ID hashes for a specified config on the server side. Basically the URI works like this: `https://doh3.dns.nextdns.io/<id>/dns-query`.
```json
{"server_name": "doh3.dns.nextdns.io/<id>"}
```
This causes a panic, stack:
```rust
QUIC Connecting
thread 'main' panicked at src\doh3\mod.rs:105:77:
called `Result::unwrap()` on an `Err` value: InvalidServerName("doh3.dns.nextdns.io/<id>")
stack backtrace:
   0:     0x7ff67e04f7bb - <unknown>
   1:     0x7ff67df5b9a9 - <unknown>
   2:     0x7ff67e0467f1 - <unknown>
   3:     0x7ff67e051527 - <unknown>
   4:     0x7ff67e05235e - <unknown>
   5:     0x7ff67e051db6 - <unknown>
   6:     0x7ff67e051d0f - <unknown>
   7:     0x7ff67e051cf6 - <unknown>
   8:     0x7ff67e08dd14 - <unknown>
   9:     0x7ff67e08e190 - <unknown>
  10:     0x7ff67df29a99 - <unknown>
  11:     0x7ff67df49281 - <unknown>
  12:     0x7ff67df45705 - <unknown>
  13:     0x7ff67df01589 - <unknown>
  14:     0x7ff67df4b031 - <unknown>
  15:     0x7ff67e08c52c - <unknown>
  16:     0x7ffac7297374 - BaseThreadInitThunk
  17:     0x7ffac889cc91 - RtlUserThreadStart
```

**Comment by radioactiveAHM** [comment]
`server_name` is the SNI (Server Name Indication) and does not function as a path. I will add `http_path` as a new option in the configuration file to support this feature.

**Comment by radioactiveAHM** [comment]
@brian6932 I added a custom HTTP path to the config file and source file. I tested it partially, but it’s not fully tested yet. Could you build and test it?

**Comment by brian6932** [comment]
Seems to work, the only thing I noticed is that if you have `/dns-query` in `custom_http_path`, the following happens on https://test.nextdns.io/.

<details>
	<summary>dns-query</summary>

```json
{"custom_http_path": "/<id>/dns-query"}
```
Response
```json
{"deviceName": "dns-query"}
```
</details>


<details>
	<summary>just id</summary>

```json
{"custom_http_path": "/<id>"}
```
Response
```json
{"clientName": "unknown-doh3"}
```
</details>

2 `/dns-query`s get appended, which results in a `clientName` being set. This isn't a problem with the code, but should be mentioned in the `README.md` documentation.

**Comment by radioactiveAHM** [comment]
I will document this. Making it more dynamic would require heap allocation, which could lead to performance loss. All custom paths must end with /dns-query. thanks for testing.
